version: '3.4'

networks:
  vtb-bank-project:
    driver: bridge

services:
  vtb-bank-db:
    image: postgres:latest
    container_name: vtb-bank-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vtb_bank_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - vtb-bank-project
    
volumes:
  app-data: